### ISSUE TITLE
Add Galaxy S108610 support

### ISSUE THREAD

**Issue by boi4** [manuel-simon/tools#1]
Hiya,
I would love to run your webcam-background script while connected to "Galaxy S108610". However, it just exits. Can u fix?
thx & LG Jan

**Comment by manuel-simon** [comment]
Hi,
I pushed a new version which allows to force execute the script, although connected to "Galaxy S108610".

You can start it using `/bin/bash webcam-background.sh force`

Best
Manuel

**Comment by boi4** [comment]
Thanks!
